### ISSUE TITLE
json parse error when calling `artist` method

### ISSUE THREAD

**Issue by aome510** [ramsayleung/rspotify#452] opened 2024-01-06 11:48 UTC
**Describe the bug**
Client now returns 
```
Bad request: json parse error: invalid type: floating point `49022656`, expected u32 at line 1 column 130: invalid type: floating point `49022656`, expected u32 at line 1 column 130
``` 
for every [`artist`](https://docs.rs/rspotify/latest/rspotify/clients/trait.BaseClient.html#method.artist) request. The reason seems to be because Spotify changes the type of `followers.total` and other fields to float.

**To Reproduce**
1. Run
```shell
curl --request GET \
        --url https://api.spotify.com/v1/artists/1dfeR4HaWDbWqFHLkxsg1d \
        --header 'Authorization: Bearer $TOKEN'
```
2. Observe that `follower.total` is not an integer. Example result:
```
{"external_urls":{"spotify":"https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d"},"followers":{"href":null,"total":4.9022656E7},"genres":["classic rock","glam rock","rock"],"href":"https://api.spotify.com/v1/artists/1dfeR4HaWDbWqFHLkxsg1d","id":"1dfeR4HaWDbWqFHLkxsg1d","images":[{"url":"https://i.scdn.co/image/b040846ceba13c3e9c125d68389491094e7f2982","height":806.0,"width":999.0},{"url":"https://i.scdn.co/image/af2b8e57f6d7b5d43a616bd1e27ba552cd8bfd42","height":516.0,"width":640.0},{"url":"https://i.scdn.co/image/c06971e9ff81696699b829484e3be165f4e64368","height":161.0,"width":200.0},{"url":"https://i.scdn.co/image/6dd0ffd270903d1884edf9058c49f58b03db893d","height":52.0,"width":64.0}],"name":"Queen","popularity":84.0,"type":"artist","uri":"spotify:artist:1dfeR4HaWDbWqFHLkxsg1d"}
```
3. Notice that some fields' type are changed to float such as `followers.total`, `popularity`

**Comment by ramsayleung** [comment] 2024-01-06 16:28
It's weird that the total and popularity are marked as integer in their [official document](https://developer.spotify.com/documentation/web-api/reference/get-an-artist), but actually return float data

**Comment by KaydaFox** [comment] 2024-01-06 17:09
im getting this same error too, think spotify may have changed something because this was all fine yesterday
response from curl:
```json
{
	"external_urls": {
		"spotify": "https://open.spotify.com/artist/4bwIf0yXJf0F9AmOl2J78M"
	},
	"followers": {
		"href": null,
		"total": 194172.0
	},
	"genres": [
		"denpa-kei",
		"rhythm game"
	],
	"href": "https://api.spotify.com/v1/artists/4bwIf0yXJf0F9AmOl2J78M",
	"id": "4bwIf0yXJf0F9AmOl2J78M",
	"images": [
		{
			"url": "https://i.scdn.co/image/ab6761610000e5ebc1f9dd30f82038e91e865d82",
			"height": 640.0,
			"width": 640.0
		},
		{
			"url": "https://i.scdn.co/image/ab67616100005174c1f9dd30f82038e91e865d82",
			"height": 320.0,
			"width": 320.0
		},
		{
			"url": "https://i.scdn.co/image/ab6761610000f178c1f9dd30f82038e91e865d82",
			"height": 160.0,
			"width": 160.0
		}
	],
	"name": "Camellia",
	"popularity": 51.0,
	"type": "artist",
	"uri": "spotify:artist:4bwIf0yXJf0F9AmOl2J78M"
}```

**Comment by ramsayleung** [comment] 2024-01-06 20:36
Yes, I can reproduce your problem now, I've submitted a ticket to Spotify to ask for clarity: https://community.spotify.com/t5/Spotify-for-Developers/The-response-type-of-artist-endpoint-is-marked-as-Integer-in/m-p/5800044

**Comment by gansheer** [comment] 2024-01-06 20:59
Hi @ramsayleung, just so you know there is an error in the issue link `https://github.com/ramsayleung/rspotify/issues/452m` (trailing **m**) in your Spotify ticket.

**Comment by ramsayleung** [comment] 2024-01-06 22:02
Thanks for your heads-up, I've revised the link to the correct one. But it's odd that a developer replied in the ticket saying what he got with `curl` was integer data instead of float data.

**Comment by Gerizard** [comment] 2024-01-06 23:08
Hey here! Developing an app for android and i have the same problem with the GETARTISTS endpoint

**Comment by aome510** [comment] 2024-01-20 19:37
I don't think Spotify will give their response anytime soon. I wonder if we have any plans to mitigate this issue @ramsayleung ?

**Comment by ramsayleung** [comment] 2024-01-23 03:25
One of the workarounds comes to my mind is converting the Integer type to float type to bypass the issue. But in my perspective, I don't think it's a great idea because

1. The SDK shouldn't silently swallow the exception caused by the Spotify server side, a better solution will be prompting the Spotify to fix the problem
2. It will introduce a breaking change in this library, which's definitely unnecessary and avoidable. 

I personally prefer to keep escalating and **making noise** to the Spotify developers, the louder noise we could make, the higher probability the Spotify team could be aware of this problem and fix it.

**Comment by ramsayleung** [comment] 2024-01-23 03:49
I've sent a message to escalate this issue to the Spotify team via this link: https://support.spotify.com/ca-en/contact-spotify-support/, here is the response from their associate:

> I already forward this issue to the team backstage. Also, the tech folks backstage confirm that they're already ahead of this and currently working for a fix. No need to worry now :)

> Also, our Tech folks are known for their hard work so this will be fixed in no time! Consider this issue resolved.

**Comment by aome510** [comment] 2024-01-23 03:53
> I've sent a message to escalate this issue to the Spotify team via this link: https://support.spotify.com/ca-en/contact-spotify-support/, here is the response from their associate:
> 
> > I already forward this issue to the team backstage. Also, the tech folks backstage confirm that they're already ahead of this and currently working for a fix. No need to worry now :)
> 
> > Also, our Tech folks are known for their hard work so this will be fixed in no time! Consider this issue resolved.

Great! Thank you @ramsayleung

**Comment by KaydaFox** [comment] 2024-01-29 17:47
> This issue is also holding up the development of a project of mine. If it isn't fixed soon by the spotify developers would rspotify support deserializing all `u32` fields with a custom `Deserializer` a la `#[serde(deserialize_with = "as_u32")]`? `as_u32` would automatically convert float fields into int ones and keep the same default behavior as before. It's pretty hacky, but it would fix the issue for now/if it arises again (im feeling pretty pessimistic lol). It'd be a less permissive version of `serde-this-or-that`'s [`as_u64`](https://docs.rs/serde-this-or-that/latest/serde_this_or_that/fn.as_u64.html).
> 
> This solution wouldn't introduce breaking changes in the API as @ramsayleung pointed out, and the fix would continue to work if spotify does get around to fixing the issue. Plus, it would only have the overhead of converting any given `f64` to a `u32`. If there's any interest in this sort of fix, let me know and I can open up a PR pretty quick.

One thing you could do as a temporary workaround is this 
```rs
        match rspotify
            .api_get(&format!("artists/{}", artist_id), &Query::new())
            .await
        {
            Ok(artist) => {
                // Manually parse the json for now
                let artist_json: Result<Value, _> = serde_json::from_str(&artist);
                match artist_json {
                }
        }```
        im not sure if its the bestt way but its what im using for now and it seems to work alright, still learning stuff lol
        but it stopped me from needing to halt development on my stuff temporarily

**Comment by ramsayleung** [comment] 2024-01-30 03:18
> One thing you could do as a temporary workaround is this

But this temporary workaround only for the **you**, the sole developer who decides to engage this approach.

I would try to implement the `as_u32` approach without imposing breaking change as a short term solution, as we actually don't know when will Spotify fix this issue.

**Comment by grantshandy** [comment] 2024-01-30 04:09
Should I contribute the fix? I can do it in the next two days unless you'd like to implement it yourself.

**Comment by ramsayleung** [comment] 2024-01-30 04:13
I could provide the code snippet for your reference, feel free to contribute and issue a PR :)

``` rust
pub mod data_type_patcher {
    use serde::{Deserialize, Deserializer};
    pub fn as_u32<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: Deserializer<'de>,
{
    let float_data: f64 = Deserialize::deserialize(deserializer)?;

    // Convert the float data to u32 (customize this conversion as needed)
    let u32_data = float_data as u32;

    Ok(u32_data)
}
}
```

**Comment by m-torhan** [comment] 2024-02-01 09:53
As I didn't see any PR related to this I let myself to implement it https://github.com/ramsayleung/rspotify/pull/457.

I tested it with https://github.com/aome510/spotify-player and it worked well.

**Comment by aome510** [comment] 2024-02-03 17:34
Look like a workaround patch landed to `master`. @ramsayleung do you have any plans to release a new version?

**Comment by ramsayleung** [comment] 2024-02-09 02:53
I am on vacation right now, I will release a new version when I am back :)

**Comment by ramsayleung** [comment] 2024-03-02 23:33
I have to say, it's "scope creep" of Spotify's bug, other developers have reported the same observation in [other endpoints](https://community.spotify.com/t5/Spotify-for-Developers/The-response-type-of-artist-endpoint-is-marked-as-Integer-in/m-p/5911749/highlight/true#M12875), it becomes less possible to be patched and bypassed individually by the community-driven library, this problem has to be fixed by the Spotify itself.

**Comment by aome510** [comment] 2024-03-02 23:40
> I have to say, it's "scope creep" of Spotify's bug, other developers have reported the same observation in [other endpoints](https://community.spotify.com/t5/Spotify-for-Developers/The-response-type-of-artist-endpoint-is-marked-as-Integer-in/m-p/5911749/highlight/true#M12875), it becomes less possible to be patched and bypassed individually by the community-driven library, this problem has to be fixed by the Spotify itself.

Yeah, I agree. At the same time, it's kinda frustrating to see that Spotify doesn't seem to take any actions.

**Comment by ramsayleung** [comment] 2024-03-03 04:01
The new version of RSpotify would like to pend for a while for the response from Spotify, since it's meanless to release a new version while Spotify keeps breaking their endpoints, the community is unable to catch up to release new patch.

**Comment by ed9w2in6** [comment] 2024-03-07 07:05
@aome510 @ramsayleung
[Seems to be fixed](https://community.spotify.com/t5/Spotify-for-Developers/duration-ms-suddenly-returning-float-instead-of-int/m-p/5911447#M12863) ^_^

As expected this is caused by some library that they are using.

I am using `spotify_player` today and found that at the the `artist` endpoint works now.

**Closed** 2024-03-08 19:16 UTC
Labels: bug, help wanted
