### ISSUE TITLE
Track object missing images field

### ISSUE THREAD

**Issue by SethGower** [ramsayleung/rspotify#64] opened 2019-11-11 22:21 UTC
According to the reference for the [track](https://developer.spotify.com/documentation/web-api/reference/tracks/get-track/) endpoint, one of the response fields is an array of `images`, which can be empty, that just stores the album art for that song. Is there any reason this isn't implemented in here?

**Comment by ramsayleung** [comment] 2019-11-12 01:56
Of course, there is no reason to not implement the `images` field. But it seems the `track object (full)` in the reference doesn't has key called `images`, but in the mocked `result` of trace endpoint, it does has a key named `images`. Well, I am confused now, should I have the `images` field or not ?

**Comment by SethGower** [comment] 2019-11-12 02:36
I have tried testing it with calls, and there is a returned parameter for `images`. I have gotten around it currently by just getting the image I want from going from track->album->image. I tried forking and implementing it myself. And was going to make a pull request. I am new to rust so it didn't work. But I may attempt again in the next couple of days if you don't get around to it.

**Comment by SethGower** [comment] 2019-11-12 02:42
I just opened an [issue](https://github.com/spotify/web-api/issues/1385) on the GH issue tracker for the web-api.

**Comment by ramsayleung** [comment] 2019-11-12 03:32
It seems the `images` field is in the [`simplified album object`](https://developer.spotify.com/documentation/web-api/reference/object-model/#album-object-simplified), but not in the `full track` object, sorry for misleading you to the wrong way. Actual, there is a field named `images` in [`simplified album object`](https://github.com/ramsayleung/rspotify/blob/de2eb74367f349603c74a6b8d1d9720700478585/src/spotify/model/album.rs#L25) or [`full album`](https://github.com/ramsayleung/rspotify/blob/de2eb74367f349603c74a6b8d1d9720700478585/src/spotify/model/album.rs#L58), I already have implemented it before.

**Comment by SethGower** [comment] 2019-11-12 13:17
I realize it is in the Album object, that is what I am using in my app instead. But I still think it is an error with spotify's documentation that the `images` part of the result for a `FullTrack` is missing.

**Comment by marioortizmanero** [comment] 2021-11-20 17:34
I'll close this for now, since it seems that even with the new reference the `images` field isn't documented: https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track. Even then, I haven't been able to reproduce it. And it seems to be a non-issue anyway.

**Closed by marioortizmanero** 2021-11-20 17:34 UTC
